version: '3'

services:
  master:
    container_name: salt_master
    image: cdalvaro/saltstack-master:2018.3.4
    restart: always
    volumes:
      - "roots/:/home/salt/data/srv"
      - "keys/:/home/salt/data/keys"
      - "logs/:/home/salt/data/logs"
    ports:
      - "4505:4505/tcp"
      - "4506:4506/tcp"
    environment:
      - DEBUG=false
      - TIMEZONE=Europe/Madrid
      - USERMAP_UID=1000
      - USERMAP_GID=1000

      - SALT_LOG_LEVEL=info
